modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
# issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="morethan50"
version="${file.jarVersion}"
displayName="More Than 50"
logoFile="pack.png"
authors="ChiefArug"
displayTest="IGNORE_SERVER_VERSION"
description='''
Let your beacons give effects to players More Than 50 blocks away!
Configure it!
Forceload it!
Infinite it!
Noop it!
And get rid of those awful particles while you are at it!

'''

[[dependencies.morethan50]]
    modId="forge"
    mandatory=true
    versionRange="[43.3.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morethan50]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
